---@generic T, R, R1
---@param f sync fun(...: T...): R1, R...
---@param ... T...
---@return boolean, R1|string, R...
function pcall(f, ...) end

--fn pcall<...T, ...R>(f: fn(...T) -> ...R, ...T) -> ...R

