-- ---@generic T, R, R1
-- ---@param f sync fun(...: T...): R1, R...
-- ---@param ... T...
-- ---@return boolean, R1|string, R...
-- function pcall(f, ...) end
--
-- --  fn pcall<...T, ...R, F>(f: F, ...T) -> ...R {} where F: fn(...T) -> ...R
-- --
-- --  fn test(a: "hi" | "hey" | "hello")
--
-- --global b = a
-- --global a = b
--
