#[derive(Clone, Debug, PartialEq)]
pub enum NumberToken {
    Int(i64),
    Float(f64),
}

//TODO: store comments for docs generation
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TokenKind {
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Comma,
    Dot,
    Minus,
    Plus,
    Semicolon,
    Slash,
    Star,
    Percent,
    Hash,
    QuestionMark,
    MarkDot,
    Colon,

    Bang,
    BangEqual,
    Equal,
    Equal2,
    Greater,
    GreaterEqual,
    Less,
    LessEqual,
    Arrow,
    FatArrow,
    Bar,
    Ampersand,
    Bar2,
    Ampersand2,

    Identifier,
    Label,
    String,
    Number,

    Let,
    Global,
    True,
    False,
    Fn,
    If,
    Else,
    For,
    While,
    Loop,
    Continue,
    Break,
    In,
    Nil,
    Print,
    Return,
    Use,
    Struct,
    Impl,
    Match,
    Extern,
    _Self,

    UnterminatedString,
    Unknown,
    EOF,
}

impl std::fmt::Display for TokenKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            TokenKind::LeftParen => write!(f, "("),
            TokenKind::RightParen => write!(f, ")"),
            TokenKind::LeftBrace => write!(f, "{{"),
            TokenKind::RightBrace => write!(f, "}}"),
            TokenKind::LeftBracket => write!(f, "["),
            TokenKind::RightBracket => write!(f, "]"),
            TokenKind::Comma => write!(f, ","),
            TokenKind::Dot => write!(f, "."),
            TokenKind::Minus => write!(f, "-"),
            TokenKind::Plus => write!(f, "+"),
            TokenKind::Semicolon => write!(f, ";"),
            TokenKind::Slash => write!(f, "/"),
            TokenKind::Star => write!(f, "*"),
            TokenKind::Percent => write!(f, "%"),
            TokenKind::Hash => write!(f, "#"),
            TokenKind::MarkDot => write!(f, "?."),
            TokenKind::Colon => write!(f, ":"),
            TokenKind::Bang => write!(f, "!"),
            TokenKind::BangEqual => write!(f, "!="),
            TokenKind::Equal => write!(f, "="),
            TokenKind::Equal2 => write!(f, "=="),
            TokenKind::Greater => write!(f, ">"),
            TokenKind::GreaterEqual => write!(f, ">="),
            TokenKind::Less => write!(f, "<"),
            TokenKind::LessEqual => write!(f, "<="),
            TokenKind::Arrow => write!(f, "->"),
            TokenKind::FatArrow => write!(f, "=>"),
            TokenKind::Bar => write!(f, "|"),
            TokenKind::Ampersand => write!(f, "&"),
            TokenKind::Bar2 => write!(f, "||"),
            TokenKind::Ampersand2 => write!(f, "&&"),
            TokenKind::Identifier => write!(f, "identifier"),
            TokenKind::Label => write!(f, "label"),
            TokenKind::String => write!(f, "string"),
            TokenKind::Number => write!(f, "number"),
            TokenKind::Let => write!(f, "let"),
            TokenKind::Global => write!(f, "global"),
            TokenKind::True => write!(f, "true"),
            TokenKind::False => write!(f, "false"),
            TokenKind::Fn => write!(f, "fn"),
            TokenKind::If => write!(f, "if"),
            TokenKind::Else => write!(f, "else"),
            TokenKind::For => write!(f, "for"),
            TokenKind::While => write!(f, "while"),
            TokenKind::Loop => write!(f, "loop"),
            TokenKind::Continue => write!(f, "continue"),
            TokenKind::Break => write!(f, "break"),
            TokenKind::In => write!(f, "in"),
            TokenKind::Nil => write!(f, "nil"),
            TokenKind::Print => write!(f, "print"),
            TokenKind::Return => write!(f, "return"),
            TokenKind::Use => write!(f, "use"),
            TokenKind::Struct => write!(f, "struct"),
            TokenKind::Impl => write!(f, "impl"),
            TokenKind::Match => write!(f, "match"),
            TokenKind::_Self => write!(f, "Self"),
            TokenKind::UnterminatedString => write!(f, "unterminated string"),
            TokenKind::Unknown => write!(f, "unknown"),
            TokenKind::EOF => write!(f, "EOF"),
            TokenKind::QuestionMark => write!(f, "?"),
            TokenKind::Extern => write!(f, "extern"),
        }
    }
}

#[derive(Clone, Debug, PartialEq)]
pub enum Token {
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Comma,
    Dot,
    Minus,
    Plus,
    Semicolon,
    Slash,
    Star,
    Percent,
    Hash,
    MarkDot,
    QuestionMark,
    Colon,

    Bang,
    BangEqual,
    Equal,
    Equal2,
    Greater,
    GreaterEqual,
    Less,
    LessEqual,
    Arrow,
    FatArrow,
    Bar,
    Ampersand,
    Bar2,
    Ampersand2,

    Identifier(String),
    Label(String),
    String(String),
    Number(NumberToken),

    Let,
    Global,
    True,
    False,
    Fn,
    If,
    Else,
    For,
    While,
    Loop,
    Continue,
    Break,
    In,
    Nil,
    Print,
    Return,
    Use,
    Struct,
    Impl,
    Match,
    Extern,
    _Self,

    UnterminatedString(String),
    Unknown(char),
    EOF,
}

impl Token {
    pub fn kind(&self) -> TokenKind {
        self.into()
    }
}

impl From<&Token> for TokenKind {
    fn from(value: &Token) -> Self {
        match value {
            Token::LeftParen => Self::LeftParen,
            Token::RightParen => Self::RightParen,
            Token::LeftBrace => Self::LeftBrace,
            Token::RightBrace => Self::RightBrace,
            Token::LeftBracket => Self::LeftBracket,
            Token::RightBracket => Self::RightBracket,
            Token::Comma => Self::Comma,
            Token::Dot => Self::Dot,
            Token::Minus => Self::Minus,
            Token::Plus => Self::Plus,
            Token::Semicolon => Self::Semicolon,
            Token::Slash => Self::Slash,
            Token::Star => Self::Star,
            Token::Percent => Self::Percent,
            Token::Hash => Self::Hash,
            Token::MarkDot => Self::MarkDot,
            Token::Colon => Self::Colon,
            Token::Bang => Self::Bang,
            Token::BangEqual => Self::BangEqual,
            Token::Equal => Self::Equal,
            Token::Equal2 => Self::Equal2,
            Token::Greater => Self::Greater,
            Token::GreaterEqual => Self::GreaterEqual,
            Token::Less => Self::Less,
            Token::LessEqual => Self::LessEqual,
            Token::Arrow => Self::Arrow,
            Token::FatArrow => Self::FatArrow,
            Token::Bar => Self::Bar,
            Token::Ampersand => Self::Ampersand,
            Token::Bar2 => Self::Bar2,
            Token::Ampersand2 => Self::Ampersand2,
            Token::Identifier(_) => Self::Identifier,
            Token::Label(_) => Self::Label,
            Token::String(_) => Self::String,
            Token::Number(_) => Self::Number,
            Token::Let => Self::Let,
            Token::Global => Self::Global,
            Token::True => Self::True,
            Token::False => Self::False,
            Token::Fn => Self::Fn,
            Token::If => Self::If,
            Token::Else => Self::Else,
            Token::For => Self::For,
            Token::While => Self::While,
            Token::Loop => Self::Loop,
            Token::Continue => Self::Continue,
            Token::Break => Self::Break,
            Token::In => Self::In,
            Token::Nil => Self::Nil,
            Token::Print => Self::Print,
            Token::Return => Self::Return,
            Token::Use => Self::Use,
            Token::Struct => Self::Struct,
            Token::Impl => Self::Impl,
            Token::Match => Self::Match,
            Token::_Self => Self::_Self,
            Token::UnterminatedString(_) => Self::UnterminatedString,
            Token::Unknown(_) => Self::Unknown,
            Token::EOF => Self::EOF,
            Token::QuestionMark => Self::QuestionMark,
            Token::Extern => Self::Extern,
        }
    }
}
