#[derive(Clone, Debug, PartialEq)]
pub enum NumberToken {
    Int(i64),
    Float(f64),
}

//TODO: store comments for docs generation
#[derive(Clone, Copy, Debug, PartialEq, Eq, strum::Display)]
pub enum TokenKind {
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Comma,
    Dot,
    Minus,
    Plus,
    Semicolon,
    Slash,
    Star,
    Percent,
    Hash,
    MarkDot,
    Colon,

    Bang,
    BangEqual,
    Equal,
    Equal2,
    Greater,
    GreaterEqual,
    Less,
    LessEqual,
    Arrow,
    FatArrow,
    Bar,
    Ampersand,
    Bar2,
    Ampersand2,

    Identifier,
    Label,
    String,
    Number,

    Let,
    Var,
    Global,
    True,
    False,
    Fn,
    If,
    Else,
    For,
    While,
    Loop,
    Continue,
    Break,
    In,
    Nil,
    Print,
    Return,
    Super,
    Use,
    Struct,
    Impl,
    Match,
    _Self,

    UnterminatedString,
    Unknown,
    EOF,
}
#[derive(Clone, Debug, PartialEq)]
pub enum Token {
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    LeftBracket,
    RightBracket,
    Comma,
    Dot,
    Minus,
    Plus,
    Semicolon,
    Slash,
    Star,
    Percent,
    Hash,
    MarkDot,
    Colon,

    Bang,
    BangEqual,
    Equal,
    Equal2,
    Greater,
    GreaterEqual,
    Less,
    LessEqual,
    Arrow,
    FatArrow,
    Bar,
    Ampersand,
    Bar2,
    Ampersand2,

    Identifier(String),
    Label(String),
    String(String),
    Number(NumberToken),

    Let,
    Var,
    Global,
    True,
    False,
    Fn,
    If,
    Else,
    For,
    While,
    Loop,
    Continue,
    Break,
    In,
    Nil,
    Print,
    Return,
    Super,
    Use,
    Struct,
    Impl,
    Match,
    _Self,

    UnterminatedString(String),
    Unknown(char),
    EOF,
}

impl From<&Token> for TokenKind {
    fn from(value: &Token) -> Self {
        match value {
            Token::LeftParen => Self::LeftParen,
            Token::RightParen => Self::RightParen,
            Token::LeftBrace => Self::LeftBrace,
            Token::RightBrace => Self::RightBrace,
            Token::LeftBracket => Self::LeftBracket,
            Token::RightBracket => Self::RightBracket,
            Token::Comma => Self::Comma,
            Token::Dot => Self::Dot,
            Token::Minus => Self::Minus,
            Token::Plus => Self::Plus,
            Token::Semicolon => Self::Semicolon,
            Token::Slash => Self::Slash,
            Token::Star => Self::Star,
            Token::Percent => Self::Percent,
            Token::Hash => Self::Hash,
            Token::MarkDot => Self::MarkDot,
            Token::Colon => Self::Colon,
            Token::Bang => Self::Bang,
            Token::BangEqual => Self::BangEqual,
            Token::Equal => Self::Equal,
            Token::Equal2 => Self::Equal2,
            Token::Greater => Self::Greater,
            Token::GreaterEqual => Self::GreaterEqual,
            Token::Less => Self::Less,
            Token::LessEqual => Self::LessEqual,
            Token::Arrow => Self::Arrow,
            Token::FatArrow => Self::FatArrow,
            Token::Bar => Self::Bar,
            Token::Ampersand => Self::Ampersand,
            Token::Bar2 => Self::Bar2,
            Token::Ampersand2 => Self::Ampersand2,
            Token::Identifier(_) => Self::Identifier,
            Token::Label(_) => Self::Label,
            Token::String(_) => Self::String,
            Token::Number(_) => Self::Number,
            Token::Let => Self::Let,
            Token::Var => Self::Var,
            Token::Global => Self::Global,
            Token::True => Self::True,
            Token::False => Self::False,
            Token::Fn => Self::Fn,
            Token::If => Self::If,
            Token::Else => Self::Else,
            Token::For => Self::For,
            Token::While => Self::While,
            Token::Loop => Self::Loop,
            Token::Continue => Self::Continue,
            Token::Break => Self::Break,
            Token::In => Self::In,
            Token::Nil => Self::Nil,
            Token::Print => Self::Print,
            Token::Return => Self::Return,
            Token::Super => Self::Super,
            Token::Use => Self::Use,
            Token::Struct => Self::Struct,
            Token::Impl => Self::Impl,
            Token::Match => Self::Match,
            Token::_Self => Self::_Self,
            Token::UnterminatedString(_) => Self::UnterminatedString,
            Token::Unknown(_) => Self::Unknown,
            Token::EOF => Self::EOF,
        }
    }
}
